"""Predeclared pretrained review cases. Diagnostic only; excluded from the PR."""
import base64
import gc
import hashlib
import io
import json
import math
import time
import urllib.request
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

from scripts.dexar_example import explain_qwen, visual_grid
from torchcam.methods import DEXAR, TAM

ROOT = Path('dexar-review-results')
ROOT.mkdir(exist_ok=True)
MODEL = 'Qwen/Qwen2.5-VL-3B-Instruct'
REVISION = '66285546d2b821cf421d4f5eb2576359d3770cd3'
CAPTION = 'Describe this image in one sentence.'
CATDOG = 'https://raw.githubusercontent.com/WalBouss/DEX-AR/07830a1e435eacde0acc68b31467681a236dc3a7/assets/cat_and_dog.jpg'
CASES = [('original_cats', 'https://raw.githubusercontent.com/huggingface/transformers/main/tests/fixtures/tests_samples/COCO/000000039769.png', CAPTION, ['cats','couch'])]
torch.manual_seed(0)
torch.set_num_threads(4)
started = time.perf_counter()
processor = AutoProcessor.from_pretrained(MODEL, revision=REVISION, min_pixels=4*28*28, max_pixels=256*28*28)
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(MODEL, revision=REVISION, torch_dtype=torch.bfloat16,
            attn_implementation={'vision_config':'sdpa'}).eval().requires_grad_(False)
model.model.float()
model.lm_head.float()
loading = time.perf_counter()-started
print('LOADED', loading, flush=True)
head = model.get_output_embeddings()
reports = []
original_call = DEXAR.__call__

def normalize(x):
    x = x-x.min(axis=(-2,-1), keepdims=True)
    divisor = x.max(axis=(-2,-1), keepdims=True)
    return np.divide(x, divisor, out=np.zeros_like(x), where=divisor>0)

def project(states, token_id):
    return [F.linear(model.model.norm(s[:, -1]) if i<len(states)-1 else s[:, -1],
                    head.weight[token_id:token_id+1], None).squeeze(-1) for i,s in enumerate(states)]

def finite_difference(block, saved, token_id, layer, mask):
    hidden, kwargs = saved
    hidden = hidden.detach().requires_grad_()
    kwargs = {**kwargs, 'past_key_value':None, 'use_cache':False, 'output_attentions':True}
    with torch.enable_grad():
        output = block(hidden, **kwargs)
        state = model.model.norm(output[0][:,-1])
        score = F.linear(state, head.weight[token_id:token_id+1]).sum()
        gradient = torch.autograd.grad(score, output[1])[0][0,:,-1]
    candidates = gradient[:, mask].abs()
    flat = int(candidates.argmax())
    h, v = divmod(flat, int(mask.sum()))
    key = int(mask.nonzero()[v])
    analytic = float(gradient[h,key])
    probability = float(output[1][0,h,-1,key])
    original_softmax = F.softmax
    eps = .001
    def evaluate(offset):
        def perturb(*args, **options):
            result = original_softmax(*args, **options)
            result = result.clone()
            result[0,h,-1,key] += offset
            return result
        F.softmax = perturb
        try:
            with torch.no_grad():
                state = model.model.norm(block(hidden.detach(), **kwargs)[0][:,-1])
                return float(F.linear(state, head.weight[token_id:token_id+1]).sum())
        finally:
            F.softmax = original_softmax
    numerical = (evaluate(eps)-evaluate(-eps))/(2*eps)
    return dict(layer=layer+1, head=h, visual_cell=v, attention_probability=probability,
                analytic=analytic, finite_difference=numerical,
                relative_error=abs(analytic-numerical)/max(abs(analytic),1e-8))

for name, url, prompt_text, targets in CASES:
    directory = ROOT/name
    directory.mkdir()
    data = urllib.request.urlopen(url).read()
    image = Image.open(io.BytesIO(data)).convert('RGB')
    image.save(directory/'input.png')
    messages = [{'role':'user','content':[{'type':'image'},{'type':'text','text':prompt_text}]}]
    prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[prompt], images=[image], return_tensors='pt')
    grid = visual_grid(model, inputs)
    started = time.perf_counter()
    generated = torch.cat((inputs['input_ids'], torch.tensor([[11613,19423,525,34644,389,264,18217,26148,448,8699,11574,14046,13,151645]])),1)
    # Exact IDs generated by the pinned model in run 37996221308; replayed without retokenization.
    generation = time.perf_counter()-started
    all_ids = generated[:,inputs['input_ids'].shape[1]:]
    eos = model.generation_config.eos_token_id
    eos = [eos] if isinstance(eos,int) else eos or []
    terminated = int(all_ids[0,-1]) in eos
    answer_ids = all_ids[:,:-1] if terminated else all_ids
    texts = [processor.tokenizer.decode([int(t)]) for t in answer_ids[0]]
    selected = {}
    for target in targets:
        found = [i for i,t in enumerate(texts) if t.strip().lower().rstrip('.,') in {target,target+'s'}]
        if found:
            selected[target] = found[0]
    print('GENERATED', name, processor.tokenizer.decode(answer_ids[0]), selected, flush=True)
    initial_mask = inputs['input_ids'][0]==model.config.image_token_id
    text_mask = ~initial_mask
    for special in processor.tokenizer.all_special_ids:
        text_mask &= inputs['input_ids'][0]!=special
    context_ids = inputs['input_ids'][:,text_mask].clone()
    context = visual = current = None
    step = 0
    tam_maps = {1:[],3:[]}
    raw_maps, reference_error, final_logits, head_counts, unrelated_maps = [],[],[],[],{}
    tam = {k:TAM(head,kernel_size=k) for k in tam_maps}
    block_inputs = {}
    def capture_block(layer):
        def capture(_module,args,kwargs):
            if step==0:
                block_inputs[layer] = (args[0].detach(),dict(kwargs))
        return capture
    block_handles = [model.model.layers[layer].register_forward_pre_hook(capture_block(layer),with_kwargs=True)
                     for layer in [0,17,35]] if name=='original_cats' else []
    def observe(_model,_args,output):
        global step, context, visual, context_ids, current
        current = output
        states = output.hidden_states[-1].detach()
        if step==0:
            visual = states[:,initial_mask].reshape(1,*grid,states.shape[-1])
            context = states[:,text_mask]
        token = int(answer_ids[0,step])
        for k,method in tam.items():
            tam_maps[k].append(method(token,visual,context,context_ids).float().cpu().numpy())
        final_logits.append(float(output.logits[0,-1,token].detach()))
        context = torch.cat((context,states[:,-1:]),1)
        context_ids = torch.cat((context_ids,answer_ids[:,step:step+1]),1)
        step += 1
    handle = model.register_forward_hook(observe)
    def checked_call(self,scores,attentions,mask,**kwargs):
        global current
        index = step-1
        rows = []
        original_grad = torch.autograd.grad
        def record(*args,**options):
            result = original_grad(*args,**options)
            rows.append(result[0][:,:,-1].detach().float().cpu().relu())
            return result
        torch.autograd.grad = record
        keep = index in selected.values()
        try:
            result = original_call(self,scores,attentions,mask,retain_graph=keep)
        finally:
            torch.autograd.grad = original_grad
        rows = torch.stack(rows)[:,0]
        v = rows[...,mask.cpu()]
        filtering = (v.amax(-1)-rows[...,~mask.cpu()].amax(-1)).relu()
        raw = (v*filtering[...,None]).sum((0,1)).reshape(*grid).numpy()
        # Reference's global affine normalization cancels in per-token min-max normalization.
        normalized_grad = (v-v.min())/(v.max()-v.min()) if v.max()>v.min() else torch.zeros_like(v)
        reference = normalize((normalized_grad*filtering[...,None]).sum((0,1)).reshape(*grid).numpy())
        np.testing.assert_allclose(result[0][0].cpu().numpy(),reference,rtol=2e-5,atol=2e-6)
        torch.testing.assert_close(scores[-1],current.logits[:,-1,int(answer_ids[0,index])],rtol=5e-5,atol=1e-4)
        raw_maps.append(raw)
        reference_error.append(float(np.max(abs(reference-result[0][0].cpu().numpy()))))
        head_counts.append(int((filtering>0).sum()))
        if keep:
            other_ids = processor.tokenizer.encode(' banana',add_special_tokens=False)
            assert len(other_ids)==1
            other_score = project(current.hidden_states[1:],other_ids[0])
            other_map,_ = original_call(self,other_score,attentions,mask)
            unrelated_maps[index] = other_map.cpu().numpy()
        current = None
        return result
    DEXAR.__call__ = checked_call
    started = time.perf_counter()
    try:
        maps,weights,sequence,timing = explain_qwen(model,inputs,answer_ids)
    finally:
        DEXAR.__call__ = original_call
        handle.remove()
        for h in block_handles:
            h.remove()
    attribution = time.perf_counter()-started
    arrays = dict(dexar=maps.cpu().numpy(),weights=weights.cpu().numpy(),sequence=sequence.cpu().numpy(),
                  raw_maps=np.stack(raw_maps),final_logits=np.array(final_logits),
                  **{'tam'+str(k):np.stack(v,axis=1) for k,v in tam_maps.items()})
    for index,other in unrelated_maps.items():
        arrays['banana_at_'+str(index)] = other
    finite = []
    if block_inputs:
        for layer,saved in block_inputs.items():
            finite.append(finite_difference(model.model.layers[layer],saved,int(answer_ids[0,0]),layer,initial_mask))
        print('FINITE_DIFFERENCES',json.dumps(finite),flush=True)
    del current,block_inputs,context,visual
    gc.collect()
    # Compare the actual raw target logit and conditional probability under the same frozen prefix.
    trim = head.register_forward_pre_hook(lambda _m,a:(a[0][:,-1:] if a[0].ndim==3 else a[0],))
    def score_image(picture,index):
        batch = processor(text=[prompt],images=[picture],return_tensors='pt')
        torch.testing.assert_close(batch['input_ids'],inputs['input_ids'])
        torch.testing.assert_close(batch['image_grid_thw'],inputs['image_grid_thw'])
        batch['input_ids'] = torch.cat((batch['input_ids'],answer_ids[:,:index]),1)
        batch['attention_mask'] = torch.ones_like(batch['input_ids'])
        with torch.no_grad():
            out = model(**batch,use_cache=False,output_attentions=False,output_hidden_states=False)
            logits = out.logits[0,-1].float()
        target = int(answer_ids[0,index])
        values,ids = logits.topk(3)
        return dict(logit=float(logits[target]),logsumexp=float(logits.logsumexp(0)),
                    log_probability=float(logits[target]-logits.logsumexp(0)),
                    competitors=[dict(id=int(i),text=processor.tokenizer.decode([int(i)]),logit=float(v)) for i,v in zip(ids,values)])
    def masked_image(score,fraction,largest=True):
        k=math.ceil(score.size*fraction)
        cells = np.argsort(score.ravel())[-k:] if largest else np.argsort(score.ravel())[:k]
        mask = np.zeros(score.size,dtype=np.uint8)
        mask[cells] = 255
        mask = np.asarray(Image.fromarray(mask.reshape(score.shape)).resize(image.size,Image.Resampling.NEAREST))>0
        pixels = np.array(image)
        pixels[mask] = np.round(pixels.mean((0,1))).astype(np.uint8)
        return Image.fromarray(pixels)
    probes = []
    try:
        for target,index in selected.items():
            baseline = score_image(image,index)
            np.testing.assert_allclose(baseline['logit'],final_logits[index],rtol=5e-5,atol=1e-4)
            candidates = [('dexar',arrays['dexar'][0,index],True),('tam3',arrays['tam3'][0,index],True),
                          ('dexar_bottom',arrays['dexar'][0,index],False),('random',np.random.default_rng(0).random(grid),True)]
            for method,score,largest in candidates:
                changed = score_image(masked_image(score,.2,largest),index)
                row = dict(target=target,position=index+1,method=method,fraction=.2,baseline=baseline,changed=changed,
                           logit_drop=baseline['logit']-changed['logit'],delta_nll=baseline['log_probability']-changed['log_probability'])
                probes.append(row)
                print('PROBE',name,json.dumps(row),flush=True)
    finally:
        trim.remove()
    report = dict(name=name,source_generation_run=37996221308,url=url,input_sha256=hashlib.sha256(data).hexdigest(),image_size=image.size,grid=grid,
                  prompt=prompt_text,answer=processor.tokenizer.decode(answer_ids[0],skip_special_tokens=True),
                  generated_ids=all_ids[0].tolist(),explained_ids=answer_ids[0].tolist(),token_text=texts,eos_terminated=terminated,
                  selected=selected,missing_targets=[t for t in targets if t not in selected],
                  seconds=dict(generation=generation,instrumented_attribution=attribution),
                  max_reference_error=max(reference_error),finite_differences=finite,head_counts=head_counts,probes=probes)
    (directory/'report.json').write_text(json.dumps(report,indent=2)+'\n')
    np.savez_compressed(directory/'maps.npz',**arrays)
    print('DEXAR_CASE_JSON:'+json.dumps(report,separators=(',',':')),flush=True)
    encoded=base64.b64encode((directory/'maps.npz').read_bytes()).decode('ascii')
    for offset in range(0,len(encoded),4096):
        print('DEXAR_CASE_CHUNK:'+name+':'+str(offset//4096)+':'+encoded[offset:offset+4096],flush=True)
    reports.append(report)
    del arrays,maps,weights,sequence,tam_maps,raw_maps,inputs,generated,answer_ids
    gc.collect()
(ROOT/'configuration.json').write_text(json.dumps(dict(model=MODEL,revision=REVISION,transformers='4.51.3',torch=torch.__version__,
                  language_dtype='float32',language_attention='eager',vision_dtype='bfloat16',vision_attention='sdpa',
                  threads=4,max_pixels=256*28*28,max_new_tokens=24,do_sample=False,loading_seconds=loading,
                  note='Predeclared demonstrations and diagnostic controls; not an accuracy benchmark.'),indent=2)+'\n')
