# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# https://github.com/conda/conda-build/pull/4480
# for conda-build > 3.21.9
# {% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
# {% set project = pyproject.get('project') %}
# {% set urls = pyproject.get('project', {}).get('urls') %}
package:
  name: torchcam
  version: "{{ environ.get('BUILD_VERSION', '0.4.1.dev0') }}"

source:
  fn: torchcam-{{ environ.get('BUILD_VERSION', '0.4.1.dev0') }}.tar.gz
  url: ../dist/torchcam-{{ environ.get('BUILD_VERSION', '0.4.1.dev0') }}.tar.gz

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.8, <4.0
    - setuptools

  run:
    - pytorch >=2.0.0, <3.0.0
    - numpy >=1.17.2, <2.0.0
    - pillow >=8.4.0, !=9.2.0
    - matplotlib >=3.0.0, <4.0.0

test:
  # Python imports
  imports:
    - torchcam
    - torchcam.methods
    - torchcam.metrics
    - torchcam.utils
  requires:
    - python

about:
  home: https://github.com/frgfm/torch-cam
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Class activation maps for your PyTorch CNN models'
  # description: |
  #   {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: https://frgfm.github.io/torch-cam/
  dev_url: https://github.com/frgfm/torch-cam
