{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project') %}
{% set urls = pyproject.get('project', {}).get('urls') %}
{% set version = environ.get('BUILD_VERSION', '0.4.1.dev0') %}
package:
  name: {{ project.get('name') }}
  version: {{ version }}

source:
  fn: {{ project.get('name') }}-{{ version }}.tar.gz
  url: ../dist/{{ project.get('name') }}-{{ version }}.tar.gz

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.8, <4.0
    - setuptools

  run:
    - pytorch >=2.0.0, <3.0.0
    - numpy >=1.17.2, <2.0.0
    - pillow >=8.4.0, !=9.2.0
    - matplotlib >=3.7.0, <4.0.0

test:
  # Python imports
  imports:
    - torchcam
    - torchcam.methods
    - torchcam.metrics
    - torchcam.utils
  requires:
    - python

about:
  home: {{ urls.get('repository') }}
  license: Apache 2.0
  license_file: {{ project.get('license', {}).get('file') }}
  summary: {{ project.get('description') }}
  # description: |
  #   {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: {{ urls.get('documentation') }}
  dev_url: {{ urls.get('repository') }}
