name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.5.13"

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install package
        run: uv pip install --system --upgrade -e .
      - name: Import package
        run: python -c "import torchcam; print(torchcam.__version__)"

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv pip install --system --upgrade setuptools wheel twine
      - run: |
          python setup.py sdist bdist_wheel
          twine check dist/*

  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        shell: bash -el {0}
        run: conda install -y conda-build conda-verify
      - name: Build conda
        shell: bash -el {0}
        run: |
          python setup.py sdist
          mkdir conda-dist
          conda env list
          conda build .conda/ -c pytorch --output-folder conda-dist
          ls -l conda-dist/noarch/*tar.bz2

  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv pip install --system --upgrade -e ".[demo]"
      - name: Run demo app
        run: |
          screen -dm streamlit run demo/app.py --server.port 8080
          sleep 10 && nc -vz localhost 8080

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Build documentation
        run: |
          make install-docs
          make full-docs
      - name: Documentation sanity check
        run: test -e docs/build/index.html || exit
